#!/usr/bin/expect -f
set ip [ lindex $argv 0 ]
set password [ lindex $argv 1 ]
set username [ lindex $argv 2 ]
set timeout -1
spawn ssh -qTNf -D 2222 $username@$ip
expect {
    "*yes/no" { send "yes\r"; exp_continue }
    "*password:" { send "$password\r" }
}
expect eof
